
 
import { AuthContextProvider } from './context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard-Openinapp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    
      <body className={inter.className}>
      <AuthContextProvider>
      {children}
      </AuthContextProvider>
      </body>
    </head>
      </html>
  )
}
